Added timing in tests. Forward to graphic tests

diff --git a/tester/roundup b/tester/roundup
--- a/tester/roundup
+++ b/tester/roundup
@@ -161,7 +161,7 @@ roundup_summarize() {
             passed=$(expr $passed + 1)
             printf "  %-48s " "$name:"
             printf "$grn[PASS]$clr\n"
-            roundup_trace < "$roundup_tmp/$name"
+            roundup_trace < "$roundup_tmp/($name)1"
             ;;
         f)
             ntests=$(expr $ntests + 1)
@@ -275,12 +275,12 @@ do
                     # where things went wrong but not in _our_ process because a
                     # failed test should not immediately fail roundup.  Each
                     # tests trace output is saved in temporary storage.
-                    set -e
-                    echo "" #I know this is hack, but it works
+                    set -xe
+                    #echo "" #I know this is hack, but it works
                     $roundup_test_name
-                ) >"$roundup_tmp/$roundup_test_name" 2>&1
+                ) >"$roundup_tmp/$roundup_test_name" 2>&1 3>"$roundup_tmp/($roundup_test_name)1"
 
-                # We need to capture the exit status before returning the `set
+		# We need to capture the exit status before returning the `set
                 # -e` mode.  Returning with `set -e` before we capture the exit
                 # status will result in `$?` being set with `set`'s status
                 # instead.
@@ -294,6 +294,7 @@ do
 
                 # This is the final step of a test.  Print its pass/fail signal
                 # and name.
+                cat "$roundup_tmp/($roundup_test_name)1"
                 if [ "$roundup_result" -ne 0 ]
                 then printf "f"
                 else printf "p"
